### ISSUE TITLE
hypixel突然断链，autoreconnect

### ISSUE THREAD

**Issue by Andymaster007** [CreatechStudio/MC-Mod-Integration#24]
### 问题描述

在Hypixel SMP里游玩时突然连接断开，再次进入后就可以正常玩了

### 复现方法

1. 启动游戏
2. 进入hypixel
3. 加入SMP
4. 游玩
5. 断链

### 你认为造成此问题的模组

1. autoreconnect

### 操作系统类型

macOS

### 操作系统版本

Monterey 12.5

### JDK版本

openjdk 17.0.4 2022-07-19 LTS OpenJDK Runtime Environment Zulu17.36+13-CA (build 17.0.4+8-LTS) OpenJDK 64-Bit Server VM Zulu17.36+13-CA (build 17.0.4+8-LTS, mixed mode, sharing)

### 启动日志

```text
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2022-12-13 08:04:51
Description: Ticking screen

java.lang.NullPointerException: Cannot invoke "autoreconnect.reconnect.ReconnectStrategy.nextAttempt()" because "this.reconnectStrategy" is null
	at autoreconnect.AutoReconnect.startCountdown(AutoReconnect.java:68)
	at net.minecraft.class_419.handler$zel001$constructor(class_419.java:1037)
	at net.minecraft.class_419.<init>(class_419.java:18)
	at net.minecraft.class_635.method_10839(class_635.java:145)
	at net.minecraft.class_2535.method_10768(class_2535.java:423)
	at net.minecraft.class_412.method_25393(class_412.java:118)
	at net.minecraft.class_310.method_1572(class_310.java:1821)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_310.method_1574(class_310.java:1821)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at autoreconnect.AutoReconnect.startCountdown(AutoReconnect.java:68)
	at net.minecraft.class_419.handler$zel001$constructor(class_419.java:1037)
	at net.minecraft.class_419.<init>(class_419.java:18)
	at net.minecraft.class_635.method_10839(class_635.java:145)
	at net.minecraft.class_2535.method_10768(class_2535.java:423)
	at net.minecraft.class_412.method_25393(class_412.java:118)
	at net.minecraft.class_310.method_1572(class_310.java:1821)
	at net.minecraft.class_437.method_25412(class_437.java:489)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_412
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_310.method_1574(class_310.java:1821)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: continuity/glass_pane_culling_fix, Default, continuity/default, armorchroma/alternative-icons, Fabric Mods, cullleaves/smartleaves, nianyekeji, Xaeros, masa-chn, siyuanheiti, Createch ClassicOre, Createch Basic, loadmyresources.hiddenpack
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2348)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (aarch64) version 12.5
	Java Version: 17.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 707757944 bytes (674 MiB) / 1342177280 bytes (1280 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 6922.81
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 581.50
	JVM Flags: 10 total; -Xmx5120m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		allmusic: AllMusic 2.6.0
		antighost: AntiGhost 1.19-fabric0.55.3-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 6.0.35
		armorchroma: Armor Chroma 1.2.2
		autofish: Autofish 0.9.5-SNAPSHOT
		autoreconnect: AutoReconnect 2.1.0-beta
		auudio: Auudio 1.0.3
		badpackets: Bad Packets 0.2.0
		betteradvancements: Better Advancements 0.2.2.142
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.3.2
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 1.4.3
		bettertaskbar: Better Taskbar 1.4
		boathud: BoatHud 1.1.1
		bookshelf: Bookshelf 16.1.11
		bsvsb: Better Sodium Video Settings Button 3.0.1
		capes: Capes 1.4.4+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.83
		carpet-extra: Carpet Extra 1.4.83
		chat_heads: Chat Heads 0.7.0
		cherishedworlds: Cherished Worlds 6.0.0+1.19.1
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.0.75
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+4
		cull-less-leaves: Cull Less Leaves 1.0.2
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		cullleaves: Cull Leaves 2.3.4
			midnightlib: MidnightLib 0.5.2
		cullparticles: Cull Particles 2.0
		customskinloader: CustomSkinLoader 14.14-SNAPSHOT-343
		customwindowtitle: Custom Window Title 1.1.1
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		draggable-resource-packs: Draggable Resource Packs 3.0.0+build.6
		drippyloadingscreen: Drippy Loading Screen 1.6.3
		durabilityviewer: Giselbaers Durability Viewer 1.19-pre2-fabric0.53.3-1.10.3
			gbfabrictools: GBfabrictools 1.3.4+1.19-pre2
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		easiervillagertrading: EasierVillagerTrading 1.19.1-fabric0.58.5-1.5.4
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.3+1.18
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		entityoutliner: Entity Outliner 1.2.4
		fabric-api: Fabric API 0.59.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.8+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.16+83a8659290
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.19+9ff28f4090
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.0+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.10+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.6+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.27+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.33+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.2+83a8659290
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.4+bd0a0d4a90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.7+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.29+a6d2f78590
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.17+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.27+9ff28f4090
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.27+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.20+1899036190
			fabric-item-api-v1: Fabric Item API (v1) 1.5.6+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.27+6bee109e90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.17+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+83a8659290
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.5+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.2+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.13+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.16+9ff28f4090
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.3+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.20+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.10+7675279690
			fabric-particles-v1: Fabric Particles (v1) 1.0.9+dc39553a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.23+23c4cfef90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.9+84f79e9d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.11+5187d39f90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.19+df3654b390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.21+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.15+9ff28f4090
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.10+e62f51a390
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.25+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.12+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.19+9ff28f4090
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.10+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.2.0+1e232e1390
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.9
		fancymenu: FancyMenu 2.13.0
		farsight: Farsight Mod 1.19.1-2.0
		fastchest: FastChest 1.3+1.19
		ferritecore: FerriteCore 4.2.1
		fmextension_audio: FancyMenu Audio Extension 1.1.1
		fpsreducer: FPS Reducer 1.19.2-2.1
		gammautils: Gamma Utils 1.6.9
		held-item-info: Held Item Info 1.3.0
		ias: In-Game Account Switcher 8.0.1
		imblocker: IMBlockerFabric 1.0.19
		indium: Indium 1.0.9+mc1.19.2
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.6.1
		iris: Iris 1.4.5
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		itemmodelfix: Item Model Fix 1.0.3+1.18
		itemscroller: Item Scroller 0.17.1
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.6.0
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		languagereload: Language Reload 1.3.2
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.12.3
		lithium: Lithium 0.9.0-SNAPSHOT
		loadmyresources: Load My Resources 1.0.4
		magiclib-1_19_2: MagicLib for 1.19.2 0.5.37
		malilib: MaLiLib 0.13.0
		masa_gadget_mod-1_19_2: Masa Gadget for 1.19.2 3.0.0-beta+bc54082
		mcwifipnp: LAN World Plug-n-Play 1.5.6
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		minecraftcapes: MinecraftCapes Mod 12.2.2
		minihud: MiniHUD 0.23.1
		modmenu: Mod Menu 4.0.5
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.19.1-0.9.0
			conditional-mixin: conditional mixin 0.3.0
		mousetweaks: Mouse Tweaks 2.22
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		nochatreports: No Chat Reports 1.19.2-v1.9.0
		notenoughanimations: NotEnoughAnimations 1.6.1
		ommc-1_19_2: Oh My Minecraft Client for 1.19.2 0.5-beta+657858c
		optigui: OptiGUI 1.1.1
			org_apache_commons_commons-text: commons-text 1.9
		orderly: Orderly 2.0.1-alpha.2+custom-1.19
		paperdoll: PaperDoll 1.1.1-mc1.19.1
		pistorder: Pistorder 1.5.0
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.19-build.47
		roughlyenoughitems: Roughly Enough Items 9.1.520
		shulkerboxtooltip: Shulker Box Tooltip 3.1.1+1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.4.4
		sodium: Sodium 0.4.4+build.18
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.12+mc1.19.2-build.72
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		tipsmod: Tips 8.0.3
		tooltipfix: ToolTip Fix 1.0.5-1.19
		tweakeroo: Tweakeroo 0.14.2
		viafabric: ViaFabric 0.4.8+15-main
			org_yaml_snakeyaml: snakeyaml 1.30
			viafabric-mc119: ViaFabric for 1.19 0.4.8+15-main
			viaversion: ViaVersion 4.4.2-SNAPSHOT
		voicechat: Simple Voice Chat 1.19.2-2.3.2
		waveycapes: WaveyCapes 1.2.0
		wi_zoom: WI Zoom 1.4-MC1.19.1
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
		wthit: wthit 5.9.0
		xaerominimap: Xaero's Minimap 22.13.0
		xaeroworldmap: Xaero's World Map 1.26.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: Createch Mod Integration Pack
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M1 GL version 4.1 Metal - 76.3, Apple
	Window size: 1440x758
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fast
	Resource Packs: continuity/glass_pane_culling_fix, vanilla, continuity/default, armorchroma/alternative-icons, Fabric Mods, cullleaves/smartleaves, file/nianyekeji, file/Xaeros, file/masa-chn, file/siyuanheiti, file/Createch ClassicOre, file/Createch Basic
	Current Language: 简体中文 (中国大陆)
	CPU: 8x Apple M1
```

### 协议

- [X] 我已查阅[常见问题解答](https://github.com/CreatechStudio/MC-Mod-Integration/issues/12)以及[Issue列表](https://github.com/CreatechStudio/MC-Mod-Integration/issues?q=is%3Aopen+is%3Aissue+label%3A%E9%97%AE%E9%A2%98)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by lightumcc** [comment]
https://github.com/CreatechStudio/MC-Mod-Integration/issues/23
